name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1"
    
    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    
    - name: Install luacheck
      run: luarocks install luacheck
    
    - name: Run luacheck
      run: luacheck .

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install stylua
      uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['nightly', 'stable']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim_version == 'stable' && 'stable' || 'nightly' }}
    
    - name: Install jj (Jujutsu)
      run: |
        curl -L https://github.com/martinvonz/jj/releases/download/v0.15.1/jj-v0.15.1-x86_64-unknown-linux-musl.tar.gz -o jj.tar.gz
        tar -xzf jj.tar.gz
        sudo mv jj /usr/local/bin/
        jj --version
    
    - name: Set up test repository
      run: |
        jj git init test-repo
        cd test-repo
        echo "test content" > test.txt
        jj describe -m "Initial commit"
        echo "modified content" > test.txt
        cd ..
    
    - name: Run functional tests
      run: |
        export CI=true
        export TEST_REPO_DIR="$(pwd)/test-repo"
        chmod +x tests/test_status_functionality.lua
        chmod +x tests/test_diff_functionality.lua
        
        # Copy tests to test-repo and modify runtime path for CI
        cp tests/test_status_functionality.lua test-repo/
        cp tests/test_diff_functionality.lua test-repo/
        
        cd test-repo
        sed -i 's/vim.cmd("set rtp+=\.")/vim.cmd("set rtp+=..")/' test_status_functionality.lua
        sed -i 's/vim.cmd("set rtp+=\.")/vim.cmd("set rtp+=..")/' test_diff_functionality.lua
        
        ./test_status_functionality.lua
        ./test_diff_functionality.lua